version: '3.7'

services:
  postgres9:
    image: postgres:9.6
    container_name: pg9_api_trivia
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=trivia_dev
    ports:
      - "4321:5432"